### ISSUE TITLE
BUG - Witnessme stalls when supplying nmap xml file

### ISSUE THREAD

**Issue by yellow-starburst** [byt3bl33d3r/WitnessMe#10]
When you submit a bug and then read the todo github documentation 
`Support NMap & .nessus files as input (Almost there, still some bugs but usable)`

Hi @byt3bl33d3r , Great tool! Wanted to help out the project and try to identify as many bugs as I can.

Background - I ran a nmap scan that created a xml file as output.
Problem - I attempted to run witnessme with a nmap xml file and witnessme would stall and never run. 
Command -  `python witnessme.py nmap.xml` and  `python3 witnessme.py nmap.xml`
Output - 
`... [INFO] - witnessme.py: main - Waiting for queue to populate...`

Also I tried to provide witnessme a different nmap format (gnmap and nmap) and it seems witnessme would run various strings not associated with any IPs. 

Installation information
fresh kali linux image and Witnessme
```
git clone https://github.com/byt3bl33d3r/WitnessMe && cd WitnessMe
pip3 install --user pipenv && pipenv install --three
pipenv shell
```

**Comment by byt3bl33d3r** [comment]
Fixed in latest  update.

Cheers
