### ISSUE TITLE
Consider using pyppeteer2

### ISSUE THREAD

**Issue by Mattwmaster58** [byt3bl33d3r/WitnessMe#13]
It looks like `pyppeteer` has been abandoned, but `pyppeteer2` seems to have fixed some of the worst issues with `pyppeteer`

**Comment by byt3bl33d3r** [comment]
Haven't heard about this, I'll take a look. Thanks for the heads up.

**Comment by Mattwmaster58** [comment]
`pyppeteer2` has gained control of `pyppeteer` on PyPi, updates incoming.
