### ISSUE TITLE
TypeError when parsing nmap file

### ISSUE THREAD

**Issue by sachinkamath** [byt3bl33d3r/WitnessMe#14]
The following error is thrown when an nmap XML is given as input : 

```
  File "/home/neo/.local/pipx/venvs/witnessme/lib/python3.8/site-packages/witnessme/parsers.py", line 109, in parser_callback
    if port["@protocol"] == "tcp" and port["state"]["@state"] == "open":
TypeError: string indices must be integers
```

**Comment by byt3bl33d3r** [comment]
@sachinkamath Can you give me the NMap command you ran to generate the XML?

**Comment by sachinkamath** [comment]
@byt3bl33d3r  I ran : `nmap -iL infile --top-ports 1000 -oX outfile`

**Comment by byt3bl33d3r** [comment]
Can you try adding the `-sV` or the `-A` flag to the NMap command?
Also is there at least 1 open port in the nmap results?

**Comment by sachinkamath** [comment]
@byt3bl33d3r I tried running nmap with both `-sV` and `-A` and the issue still seems to be there. I tested this locally with a single port open.

Attaching nmap xml file for your reference

[nmap_test.log](https://github.com/byt3bl33d3r/WitnessMe/files/4900730/nmap_test.log)

**Comment by sachinkamath** [comment]
I think I have narrowed down on the issue. When there is only a single port available, `item["ports"]["port"]` is an OrderedDict object, so `for port in ports` doesn't work as intended.

The hack in #15 seems to work for me.

**Comment by byt3bl33d3r** [comment]
Latest push should have fixed it. Thanks for giving me the Nmap XML, helped a ton.
Cheers
