### ISSUE TITLE
Adding --no-sandbox param to the pyppeteer

### ISSUE THREAD

**Issue by mmetince** [byt3bl33d3r/WitnessMe#3]
When you try to run witness me with  root user, pyppeteer will be ignoring to initiate chrome process. In order to avoid from that, we gotta pass `args=['--no-sandbox']` to `launch()` function.

https://github.com/byt3bl33d3r/WitnessMe/blob/c8086041a418026b1b4b13afeb253ee6cdcef188/witnessme.py#L139

I do propose following fix. I've tested it on locally.

```
browser = await pyppeteer.launch(headless=True, ignoreHTTPSErrors=True, args=['--no-sandbox'])
```

**Comment by mmetince** [comment]
Actually #2 related with that issue.

**Comment by korang** [comment]
The fix above worked for me

**Comment by byt3bl33d3r** [comment]
Ah, I never ran it with root privs. That explains why I didn't run into this. Thanks, I'll push a fix soon.

**Comment by byt3bl33d3r** [comment]
Done. Thanks
