### ISSUE TITLE
Ability to output to CSV or XML --feature request

### ISSUE THREAD

**Issue by nullenc0de** [byt3bl33d3r/WitnessMe#5]
The tool makes a very useful graph output. Would it be possible to leverage it in another format that is shareable to people that don't have WitnessMe installed?

Specifically, I was hoping for a CSV or XML output.

**Comment by byt3bl33d3r** [comment]
I like the idea. Will add it to the TO DO list :)
Thanks

**Comment by byt3bl33d3r** [comment]
CSV reporting was added to the latest update.
Thanks!
