### ISSUE TITLE
websocket installation fails during pipenv install --three

### ISSUE THREAD

**Issue by secureideas** [byt3bl33d3r/WitnessMe#8]
I am trying to add WitnessMe to the SamuraiWTF build.   We are getting a failure during the set up from pipenv failing to find a matching version of websockets.  

Basically the error is:

"ERROR: Could not find a version that satisfies the requirement websocket==8.1" It then lists "from versions" and that only goes to 7.0.  This is a Debian system from SamuraiWTF

**Comment by byt3bl33d3r** [comment]
@secureideas If I had to guess it's because you don't have Python >= 3.7. Can you verify what versions of Python you have on the system? 

Thanks

**Comment by secureideas** [comment]
Nice catch.  3.5.3.  I will see if we can upgrade with this version of Debian.

**Comment by secureideas** [comment]
Looks like that was the issue.  Thanks!
